config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/' => 'home#index'
  get '/users/hero_index' => 'users#hero_index'
  get '/users/volunteer_index' => 'users#volunteer_index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :zip_code, length: { is: 5 }
  validates :cell_number, length: { is: 12 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # def new
  #   respond_to do |f|
  #     f.html { redirect_to '/' }
  #     f.js { render 'new_password_index.js.erb' }
  #   end
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  def create
    @user = User.create(user_params)
    if @user.valid?
      sign_in @user
      redirect_to '/'
    else
      flash[:alert] = @user.errors.full_messages
      redirect_to '/users/sign_up'
    end
  end

  private

  def user_params
    params.require(:user).permit(:zip_code, :hero, :volunteer, :email, :password, :password_confirmation, :location, :children_ages, :range_possible_hours, :gender, :experience, :school, :age_range_kids_sit, :first_name, :last_name, :county, :cell_number, :services_needed_or_provided, :transportation, :availability, :age, :max_number_kids_sit, :zip_code, :babysitting, :grocery_shopping, :e_learning_assistance, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :morning, :afternoon, :evening, :night, :other, :c_morning, :c_afternoon, :c_evening, :c_night, :age_16, :age_17, :age_18_up, :yes_transit, :no_transit)
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :authenticate_user!

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  def create
    if user_signed_in?
      redirect_to "/"
    else
      respond_to do |f|
        f.html { redirect_to '/users/sign_in' }
        f.js { render 'errors_create.js.erb' }
      end
    end
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  private

  def user_params
    params.require(:user).permit(:zip_code, :hero, :volunteer, :email, :password, :password_confirmation, :location, :children_ages, :range_possible_hours, :gender, :experience, :school, :age_range_kids_sit, :first_name, :last_name, :county, :cell_number, :services_needed_or_provided, :transportation, :availability, :age, :max_number_kids_sit, :zip_code, :babysitting, :grocery_shopping, :e_learning_assistance, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :morning, :afternoon, :evening, :night, :other, :c_morning, :c_afternoon, :c_evening, :c_night, :age_16, :age_17, :age_18_up, :yes_transit, :no_transit, :remember_me)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :authenticate_user!

  def hero_index
    @users = users(user_params)

    respond_to do |f|
      f.html { redirect_to '/' }
      f.js { render 'hcw_index.js.erb' }
    end
  end

  def volunteer_index
    @users = users(user_params)

    respond_to do |f|
      f.html { redirect_to '/' }
      f.js { render 'sitter_index.js.erb' }
    end
  end

  def users(_parameters)
    new_hash = {}

    user_params.each do |k, v|
      new_hash[k.to_sym] = v.to_i if v.to_i >= 1
    end

    User.where(new_hash)
  end

  private

  def user_params
    params.require(:user).permit(:zip_code, :hero, :volunteer, :email, :password, :password_confirmation, :location, :children_ages, :range_possible_hours, :gender, :experience, :school, :age_range_kids_sit, :first_name, :last_name, :county, :cell_number, :services_needed_or_provided, :transportation, :availability, :age, :max_number_kids_sit, :zip_code, :babysitting, :grocery_shopping, :e_learning_assistance, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :morning, :afternoon, :evening, :night, :other, :c_morning, :c_afternoon, :c_evening, :c_night, :age_16, :age_17, :age_18_up, :yes_transit, :no_transit)
  end
end

app/views/users/_hcw_results.html.erb
<% if @users.length == 0 %>
  <h1>No results.</h1>
<% end %>
<div class="results">
  <% @users.each do |user| %>
  <div class="one_result">
  <div class="yellow_rectangle"></div>
    <% if user_signed_in? && user.zip_code %>
      Zip Code: <%= user.zip_code %><br>
    <% end %>
    <% if user.gender %>
      Gender: <% user.gender %><br>
    <% end %>
    <% if user.sunday == 1 %>
      Needs Help on Sunday<br>
    <% end %>
    <% if user.monday == 1 %>
      Needs Help on Monday<br>
    <% end %>
    <% if user.tuesday == 1 %>
      Needs Help on Tuesday<br>
    <% end %>
    <% if user.wednesday == 1 %>
      Needs Help on Wednesday<br>
    <% end %>
    <% if user.thursday == 1 %>
      Needs Help on Thursday<br>
    <% end %>
    <% if user.friday == 1 %>
      Needs Help on Friday<br>
    <% end %>
    <% if user.saturday == 1 %>
      Needs Help on Saturday<br>
    <% end %>
    <% if user.morning == 1%>
      Needs Help in the Morning<br>
    <% end %>
    <% if user.afternoon == 1%>
      Needs Help in the Afternoon<br>
    <% end %>
    <% if user.evening == 1%>
      Needs Help in the Evening<br>
    <% end %>
    <% if user.night == 1%>
      Needs Help at Night<br>
    <% end %>
    <% if user.first_name %>
      Name: <%= user.first_name%><br>
    <% end %>
    <% if user_signed_in? && user.cell_number %>
      Phone Number: <%= user.cell_number %><br>
    <% end %>
    <% if user.yes_transit == 1%>
      Transportation is Necessary<br>
    <% end %>
    <% if user.no_transit == 1%>
      Transportation is Not Necessary<br>
    <% end %>
    <% if user.babysitting == 1%>
      Needs Babysitting<br>
    <% end %>
    <% if user.grocery_shopping == 1%>
      Needs Grocery Shopping<br>
    <% end %>
    <% if user.e_learning_assistance == 1%>
      Needs Assistance With E-Learning<br>
    <% end %>
  </div>
 <% end %>
</div>

app/views/users/_hcw_results_html.erb
<div class="login_title_rosie">
  <div class="login_div">
    <h2>COVID-19 Volunteers For Victory</h1>
    <h2>Log in</h2>
  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>
    <br>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password, autocomplete: "current-password" %>
    </div>
  <br>
    <% if devise_mapping.rememberable? %>
      <div class="field">
        <%= f.check_box :remember_me %>
        <%= f.label :remember_me %>
      </div>
    <% end %>  

    <br>  

    <div class="actions">
      <%= f.submit "Log in" %>
    </div>
  <% end %>  

  <br>  

  <%= render "users/shared/links" %>

  <br>

  </div>

  <br>

  <div class="title_rosie">
    Hi, I'm Jordan Colgan and I came up with this website so we can match volunteers willing to help the healthcare heroes and essential worker warriors who are working around the clock to fight and win the war against COVID-19. THANK YOU.

    <br><br>

    As a high school junior in Cook County, IL, I have friends whose parents are balancing increased work hours with kids who are suddenly at home and they need assistance.
    <br>
    <img src="https://images.fastcompany.net/image/upload/w_700,f_auto,q_auto,fl_lossy/wp-cms/uploads/2018/06/p-2-90176641-what-the-iconic-rosie-the-riveter-poster-tktktk-1.jpg">
  </div>

  <div class="disclaimer_div">
    DISCLAIMER: This site is for the purpose of helping working parents locate members of the community who are willing to assist. We do not run individual background checks on the individuals who have reached out, and rely on the goodwill of participants to make this exercise successful. We are asking participants who are over 18 to provide references, and we urge those seeking services to do your own due diligence before making any hiring decisions.    

    Please remember that this program is designed to help students and families through this challenging time in which school has transitioned to an online learning system. Your family and education needs will still be in the forefront. Our priority remains the health and safety of everyone involved and in order to keep everyone as safe as possible we ask that if you or anyone has come in close contact with you does not feel well that you stay at home and contact us to provide accomodation for your family. This program is completely voluntary and if you feel uncomfortable at any time you may cease participation. In participating in this program you enter your partner's home and you are taking responsibility for your own health and safety. All of your information will be protected and will only be shared with the family in which you become paired with. Typing your name below serves as your electronic signature acknowledging all the statements above. *
  </div>
</div>

<div class="hero_volunteer_div">
    <div class="hero_div">
    <%= form_with model: User, url: '/users/volunteer_index', method: :get, remote: true do |f| %>
      <br>
      I need a Volunteer!<%= f.check_box :hero, placeholder: "hero" %><br><br>
      Zip Code 
      <%= f.text_field :zip_code, placeholder: "Zip Code XXXXX:" %><br><br>  

      Services Needed: Babysitting<%= f.check_box :babysitting, placeholder: "babysitting" %>
      Grocery Shopping<%= f.check_box :grocery_shopping, placeholder: "grocery_shopping" %>
      E-Learning Assistance<%= f.check_box :e_learning_assistance, placeholder: "e_learning_assistance" %><br><br>
      I Need Someone Available on the Following Days:<br>
      Sunday<%= f.check_box :sunday, placeholder: "sunday" %>
      Monday<%= f.check_box :monday, placeholder: "monday" %>
      Tuesday<%= f.check_box :tuesday, placeholder: "tuesday" %>
      Wednesday<%= f.check_box :wednesday, placeholder: "wednesday" %>
      Thursday<%= f.check_box :thursday, placeholder: "thursday" %>
      Friday<%= f.check_box :friday, placeholder: "friday" %>
      Saturday<%= f.check_box :saturday, placeholder: "saturday" %><br><br>
      I Need Someone Available at the Following Times:<br>
      Morning<%= f.check_box :morning, placeholder: "morning" %>
      Afternoon<%= f.check_box :afternoon, placeholder: "afternoon" %>
      Evening<%= f.check_box :evening, placeholder: "evening" %>
      Night<%= f.check_box :night, placeholder: "night" %><br><br>  

      I Need Someone With Transportation<%= f.check_box :yes_transit, placeholder: "yes_transit" %>
      I Don't Need Someone With Transportation<%= f.check_box :no_transit, placeholder: "no_transit" %><br><br>
      <div class="search_div"><%= f.submit "Search" %></div><br>
    <% end %>
  </div>

    <div class="volunteer_div">
    <%= form_with model: User, url: '/users/hero_index', method: :get, remote: true do |f| %>
      <br>
      I am Willing to Volunteer<%= f.check_box :volunteer, placeholder: "volunteer" %><br><br>
      Zip Code <%= f.text_field :zip_code, placeholder: "Zip Code XXXXX:" %><br><br>
      Services Provided: Babysitting<%= f.check_box :babysitting, placeholder: "babysitting" %>
      Grocery Shopping<%= f.check_box :grocery_shopping, placeholder: "grocery_shopping" %>
      E-Learning Assistance<%= f.check_box :e_learning_assistance, placeholder: "e_learning_assistance" %><br><br>
      I am Available on the Following Days:<br>
      Sunday<%= f.check_box :sunday, placeholder: "sunday" %>
      Monday<%= f.check_box :monday, placeholder: "monday" %>
      Tuesday<%= f.check_box :tuesday, placeholder: "tuesday" %>
      Wednesday<%= f.check_box :wednesday, placeholder: "wednesday" %>
      Thursday<%= f.check_box :thursday, placeholder: "thursday" %>
      Friday<%= f.check_box :friday, placeholder: "friday" %>
      Saturday<%= f.check_box :saturday, placeholder: "saturday" %><br><br>
      I am Available at the Following Times:<br>
      Morning<%= f.check_box :morning, placeholder: "morning" %>
      Afternoon<%= f.check_box :afternoon, placeholder: "afternoon" %>
      Evening<%= f.check_box :evening, placeholder: "evening" %>
      Night<%= f.check_box :night, placeholder: "night" %><br><br>
      I Have Transportation<%= f.check_box :yes_transit, placeholder: "yes_transit" %>
      I Don't Have Transportation<%= f.check_box :no_transit, placeholder: "no_transit" %><br><br>
      <div class="search_div"><%= f.submit "Search" %></div><br>
    <% end %>
  </div>
</div>
<div id="search-results-append"></div>

app/views/users/_sitter_results.html.erb
<% if @users.length == 0 %>
    <h1>No results.</h1>
<% end %>
<div class="results">
  <% @users.each do |user| %>
    <div class="one_result">
    <div class="yellow_rectangle"></div>
    <% if user_signed_in? && user.zip_code %>
      Zip Code: <%= user.zip_code %><br>
    <% end %>
    <% if user.gender %>
      Gender: <% user.gender %><br>
    <% end %>
    <% if user.sunday == 1 %>
      Available Sunday<br>
    <% end %>
    <% if user.monday == 1 %>
      Available Monday<br>
    <% end %>
    <% if user.tuesday == 1 %>
      Available Tuesday<br>
    <% end %>
    <% if user.wednesday == 1 %>
      Available Wednesday<br>
    <% end %>
    <% if user.thursday == 1 %>
      Available Thursday<br>
    <% end %>
    <% if user.friday == 1 %>
      Available Friday<br>
    <% end %>
    <% if user.saturday == 1 %>
      Available Saturday<br>
    <% end %>
    <% if user.morning == 1%>
      Available in the Morning<br>
    <% end %>
    <% if user.afternoon == 1%>
      Available in the Afternoon<br>
    <% end %>
    <% if user.evening == 1%>
      Available in the Evening<br>
    <% end %>
    <% if user.night == 1%>
      Available at Night<br>
    <% end %>
    <% if user.experience %>
      Experience: <%= user.experience%><br>
    <% end %>
    <% if user.school %>
      School: <%= user.school%><br>
    <% end %>
    <% if user.age_range_kids_sit %>
      Will sit for this many children: <%= user.age_range_kids_sit%><br>
    <% end %>
    <% if user.first_name %>
      Name: <%= user.first_name%><br>
    <% end %>
    <% if user.county %>
      County: <%= user.county %><br>
    <% end %>
    <% if user_signed_in? && user.cell_number %>
      Phone Number: <%= user.cell_number %><br>
    <% end %>
    <% if user.yes_transit == 1%>
      Has Transportation<br>
    <% end %>
    <% if user.no_transit == 1%>
      Does Not Have Transportation<br>
    <% end %>
    <% if user.age_16 == 1%>
      Age: 16<br>
    <% end %>
    <% if user.age_17 == 1%>
      Age: 17<br>
    <% end %>
    <% if user.age_18_up == 1%>
      Age: 18+<br>
    <% end %>
    <% if user.babysitting == 1%>
      Can Babysit<br>
    <% end %>
    <% if user.grocery_shopping == 1%>
      Can Grocery Shop<br>
    <% end %>
    <% if user.e_learning_assistance == 1%>
      Can Assist With E-Learning<br>
    <% end %>
  </div>
 <% end %>
</div>

app/views/users/_sitter_results_html.erb
<% if @users.length == 0%>
  No Results.
<% end %>
<div class="results">
  <% @users.each do |user| %>
    <div class="one_result">
    <% if user.zip_code %>
      Zip Code: <%= user.zip_code %><br>
    <% end %>
    <% if user.gender %>
      Gender: <% user.gender %><br>
    <% end %>
    <% if user.sunday == 1 %>
      Available Sunday<br>
    <% end %>
    <% if user.monday == 1 %>
      Available Monday<br>
    <% end %>
    <% if user.tuesday == 1 %>
      Available Tuesday<br>
    <% end %>
    <% if user.wednesday == 1 %>
      Available Wednesday<br>
    <% end %>
    <% if user.thursday == 1 %>
      Available Thursday<br>
    <% end %>
    <% if user.friday == 1 %>
      Available Friday<br>
    <% end %>
    <% if user.saturday == 1 %>
      Available Saturday<br>
    <% end %>
    <% if user.morning == 1%>
      Available in the Morning<br>
    <% end %>
    <% if user.afternoon == 1%>
      Available in the Afternoon<br>
    <% end %>
    <% if user.evening == 1%>
      Available in the Evening<br>
    <% end %>
    <% if user.night == 1%>
      Available at Night<br>
    <% end %>
    <% if user.experience %>
      Experience: <%= user.experience%><br>
    <% end %>
    <% if user.school %>
      School: <%= user.school%><br>
    <% end %>
    <% if user.age_range_kids_sit %>
      Will sit for this many children: <%= user.age_range_kids_sit%><br>
    <% end %>
    <% if user.first_name %>
      Name: <%= user.first_name%><br>
    <% end %>
    <% if user.county %>
      County: <%= user.county %><br>
    <% end %>
    <% if user.cell_number %>
      Phone Number: <%= user.cell_number %><br>
    <% end %>
    <% if user.yes_transit == 1%>
      Has Transportation<br>
    <% end %>
    <% if user.no_transit == 1%>
      Does Not Have Transportation<br>
    <% end %>
    <% if user.age_16 == 1%>
      Age: 16<br>
    <% end %>
    <% if user.age_17 == 1%>
      Age: 17<br>
    <% end %>
    <% if user.age_18_up == 1%>
      Age: 18+<br>
    <% end %>
    <% if user.babysitting == 1%>
      Can Babysit<br>
    <% end %>
    <% if user.grocery_shopping == 1%>
      Can Grocery Shop<br>
    <% end %>
    <% if user.e_learning_assistance == 1%>
      Can Assist With E-Learning<br>
    <% end %>
  </div>
 <% end %>
</div>

app/views/users/hcw_index.js.erb
$("#search-results-append").empty();
$("#search-results-append").append("<%= j render(:partial => 'users/hcw_results') %>");
window.scrollBy(0, 530);

app/views/users/sitter_index.js.erb
$("#search-results-append").empty();
$("#search-results-append").append("<%= j render(:partial => 'users/sitter_results') %>");
window.scrollBy(0, 530);